sonar.organization=ptdat30
sonar.projectKey=ptdat30_Test_DoctorBooking_2026
sonar.projectName=Test_DoctorBooking_2026

# Path to the source directories
sonar.sources=.

# Exclusions (optional but recommended for faster analysis)
sonar.exclusions=**/node_modules/**, **/dist/**, **/.git/**, **/target/**, **/bin/**
