sonar.organization=ptdat30
sonar.projectKey=ptdat30_Test_DoctorBooking_2026
sonar.projectName=Test_DoctorBooking_2026

# Path to the source directories
sonar.sources=backend/src/main/java,frontend/src

# Java compiled classes directory (mandatory for SonarQube analysis on Java projects)
sonar.java.binaries=backend/target/classes

# Exclusions (optional but recommended for faster analysis)
sonar.exclusions=**/node_modules/**, **/dist/**, **/.git/**, **/target/**, **/bin/**, **/postman/**, **/*.png, **/*.jpg, **/*.jpeg, **/*.gif, **/*.svg, **/*.mp4, **/*.html, backend/src/test/**, frontend/src/assets/**
