import {
  ArrowLeft,
  Briefcase,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  Circle,
  Clock,
  CreditCard,
  DollarSign,
  Edit2,
  Eye,
  EyeOff,
  FileText,
  Gift,
  Hash,
  Heart,
  Info,
  List,
  LayoutDashboard,
  LogOut,
  MessageCircle,
  MessageSquare,
  RefreshCw,
  RotateCw,
  Search,
  Send,
  Shield,
  Star,
  Trash2,
  User,
  UserCheck,
  UserPlus,
  Users,
  X,
  XCircle,
  AlertCircle,
  CheckSquare,
} from 'lucide-react';

const ICON_MAP = {
  'arrow-left': ArrowLeft,
  'edit-2': Edit2,
  eye: Eye,
  'eye-off': EyeOff,
  'trash-2': Trash2,
  'user-plus': UserPlus,
  search: Search,
  'chevron-down': ChevronDown,
  x: X,
  list: List,
  calendar: Calendar,
  'x-circle': XCircle,
  user: User,
  briefcase: Briefcase,
  'file-text': FileText,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  'check-circle': CheckCircle,
  clock: Clock,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  hash: Hash,
  'check-square': CheckSquare,
  info: Info,
  'rotate-cw': RotateCw,
  'refresh-cw': RefreshCw,
  star: Star,
  heart: Heart,
  users: Users,
  'user-check': UserCheck,
  gift: Gift,
  'alert-circle': AlertCircle,
  'log-out': LogOut,
  send: Send,
  check: Check,
  layout: LayoutDashboard,
  shield: Shield,
};

/** Thay thế `<i data-feather="...">` — dùng lucide-react thống nhất */
const ShellIcon = ({ name, className = 'w-4 h-4', strokeWidth = 1.75 }) => {
  const Icon = ICON_MAP[name] || Circle;
  return <Icon className={className} strokeWidth={strokeWidth} />;
};

export default ShellIcon;
